# Generated by Django 5.2.5 on 2025-08-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mk', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.banksoal')),
                ('semester_akademik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.semesterakademik')),
            ],
        ),
        migrations.CreateModel(
            name='AspekUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot', models.IntegerField()),
                ('order', models.IntegerField()),
                ('durasi', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aspek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.bankaspekpenilaian')),
                ('jadwal_ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian.jadwalujian')),
            ],
        ),
        migrations.CreateModel(
            name='KelompokUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelompok', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jadwal_ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian.jadwalujian')),
            ],
        ),
    ]
