"""
Django settings for osce_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$n0p8!h_5e53@^k=w-!z7=d&44x9hzube0xvql*pf5vmfzr+@i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost.ums.ac.id','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'landing', 'penilaian', 'ujian', 'alokasi', 'master'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'osce_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'osce_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "OSCE Keperawatan",
    "SITE_HEADER": "OSCE Keperawatan Management System",
    "SITE_URL": "/",
    "SIDEBAR_TOGGLE_ENABLED": False,  # Disable sidebar toggle buttons
    "SITE_ICON": {
        "light": lambda request: static("images/logo-light.svg"),
        "dark": lambda request: static("images/logo-dark.svg"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("images/logo-light.svg"),
        "dark": lambda request: static("images/logo-dark.svg"),
    },
    "SITE_SYMBOL": "🏥",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_TIMEZONE_WARNING": False,  # Disable timezone warning
    "ENVIRONMENT": "osce_project.utils.environment_callback",
    # "DASHBOARD_CALLBACK": "osce_project.utils.dashboard_callback",  # Temporarily disabled
    "LOGIN": {
        "image": "path/to/login-bg.jpg",
        "redirect_after": "/admin/",
    },
    "STYLES": [
        lambda request: static("css/custom.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/custom.js"),
    ],
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254", 
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84"
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇺🇸",
                "fr": "🇫🇷",
                "nl": "🇳🇱",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Dashboard",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Master Data",
                "separator": True,
                "items": [
                    {
                        "title": "Fakultas",
                        "icon": "school",
                        "link": "/admin/master/fakultas/",
                    },
                    {
                        "title": "Program Studi",
                        "icon": "book",
                        "link": "/admin/master/programstudi/",
                    },
                    {
                        "title": "Semester Akademik",
                        "icon": "calendar_month",
                        "link": "/admin/master/semesterakademik/",
                    },
                    {
                        "title": "Mahasiswa",
                        "icon": "person",
                        "link": "/admin/master/mahasiswa/",
                    },
                    {
                        "title": "Dosen",
                        "icon": "person_outline",
                        "link": "/admin/master/dosen/",
                    },
                ],
            },
            {
                "title": "Bank Soal",
                "separator": True,
                "items": [
                    {
                        "title": "Kategori Soal",
                        "icon": "category",
                        "link": "/admin/master/kategorisoal/",
                    },
                    {
                        "title": "Bank Soal",
                        "icon": "quiz",
                        "link": "/admin/master/banksoal/",
                    },
                    {
                        "title": "Bank Aspek Penilaian",
                        "icon": "checklist",
                        "link": "/admin/master/bankaspekpenilaian/",
                    },
                ],
            },
            {
                "title": "Ujian",
                "separator": True,
                "items": [
                    {
                        "title": "Jadwal Ujian",
                        "icon": "schedule",
                        "link": "/admin/ujian/jadwalujian/",
                    },
                    {
                        "title": "Aspek Ujian",
                        "icon": "assignment",
                        "link": "/admin/ujian/aspekujian/",
                    },
                    {
                        "title": "Kelompok Ujian",
                        "icon": "group",
                        "link": "/admin/ujian/kelompokujian/",
                    },
                ],
            },
            {
                "title": "Alokasi",
                "separator": True,
                "items": [
                    {
                        "title": "Alokasi Mahasiswa",
                        "icon": "person_add",
                        "link": "/admin/alokasi/alokasimahasiswa/",
                    },
                    {
                        "title": "Alokasi Dosen",
                        "icon": "supervisor_account",
                        "link": "/admin/alokasi/alokasidosen/",
                    },
                ],
            },
            {
                "title": "Penilaian",
                "separator": True,
                "items": [
                    {
                        "title": "Nilai Mahasiswa",
                        "icon": "grade",
                        "link": "/admin/penilaian/nilaimahasiswa/",
                    },
                ],
            },
            {
                "title": "System",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": "Groups",
                        "icon": "security",
                        "link": "/admin/auth/group/",
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "master.fakultas",
                "master.programstudi",
            ],
            "items": [
                {
                    "title": "Fakultas",
                    "link": "/admin/master/fakultas/",
                },
                {
                    "title": "Program Studi", 
                    "link": "/admin/master/programstudi/",
                },
            ],
        },
        {
            "models": [
                "ujian.jadwalujian",
                "ujian.aspekujian", 
                "ujian.kelompokujian",
            ],
            "items": [
                {
                    "title": "Jadwal Ujian",
                    "link": "/admin/ujian/jadwalujian/",
                },
                {
                    "title": "Aspek Ujian",
                    "link": "/admin/ujian/aspekujian/",
                },
                {
                    "title": "Kelompok Ujian",
                    "link": "/admin/ujian/kelompokujian/",
                },
            ],
        },
    ],
}
