# Generated by Django 5.2.5 on 2025-08-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('ujian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlokasiDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.dosen')),
                ('jadwal_ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian.jadwalujian')),
                ('kelompok_ujian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ujian.kelompokujian')),
            ],
        ),
        migrations.CreateModel(
            name='AlokasiMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jadwal_ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian.jadwalujian')),
                ('kelompok_ujian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ujian.kelompokujian')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.mahasiswa')),
            ],
        ),
    ]
